#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The plugin these libraries were built for. Nothing else here names it.

PLUGIN_NAME='unsolicited-comments'
PLUGIN_PREFIX='UNSOLICITED_COMMENTS'
PLUGIN_DISPLAY_NAME='unsolicited-comments'

plugin_setting_default() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' '{state}/notes' ;;
    UPDATE_CHECK) printf '%s' 'on' ;;
    UPDATE_CHECK_DAYS) printf '%s' '1' ;;
    VERSION_SOURCE) printf '%s' 'https://raw.githubusercontent.com/justinkek/unsolicited-comments/main/package.json' ;;
  esac
}

plugin_setting_kind() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' 'text' ;;
    UPDATE_CHECK) printf '%s' 'switch' ;;
    UPDATE_CHECK_DAYS) printf '%s' 'count' ;;
    VERSION_SOURCE) printf '%s' 'text' ;;
  esac
}

plugin_setting_values() {
  case "$1" in
  esac
}

plugin_session_start_hooks() {
  printf '%s\n' 'load-rules.sh'
}
